Updated the Info

diff --git a/charts/spinnaker/templates/configmap/halyard-init-script.yaml b/charts/spinnaker/templates/configmap/halyard-init-script.yaml
--- a/charts/spinnaker/templates/configmap/halyard-init-script.yaml
+++ b/charts/spinnaker/templates/configmap/halyard-init-script.yaml
@@ -9,12 +9,9 @@ data:
     #!/bin/bash
     {{- if .Values.halyard.gitops.enabled }}
     rm -rf /tmp/spinnaker/.hal
-    kubectl get secret opsmx-gitops-auth -n ${SPINNAKER_NAMESPACE}
-    if [[ $? != 0 ]]; then
-       echo "Opsmx Gitops Auth Secret not found"
-       echo "Please create a secret"
-       exit 4
-    else
+    secret=$(kubectl get secret opsmx-gitops-auth -n {{ .Release.Namespace }} | awk '{print $1}' | tail -n +2)
+    if [[ "$secret" == "opsmx-gitops-auth" ]]; then
+      echo "INFO: $secret is present"
       GIT_USER=`echo $GIT_USER | sed 's/ *$//g'`
       GIT_TOKEN=`echo $GIT_TOKEN | sed 's/ *$//g'`
       git -c {{ .Values.halyard.gitops.repo.configArgs }} clone $GIT_CLONE_PARAM -b {{ .Values.halyard.gitops.repo.halConfigBranch }} /tmp/spinnaker/test 2>/tmp/tmp.log
@@ -28,6 +25,10 @@ data:
          echo "To expedite the restart, wait for 60 seconds and delete the spinnaker-halyard-0 pod from another window"
          exit 4
       fi
+    else
+      echo "$secret not found"
+      echo "Please create a secret"
+      exit 4
     fi
     cp -r /tmp/spinnaker/test// /tmp/spinnaker/.hal
     rm -rf /tmp/spinnaker/test
@@ -36,6 +37,7 @@ data:
     cp /tmp/spinnaker/.hal/halyard.yaml /tmp/config
     fi
     sed -i s/SPINNAKER_NAMESPACE/${SPINNAKER_NAMESPACE}/ /tmp/spinnaker/.hal/config
+    echo "Halyard is configured with Gitrepo"
     {{- else }}
     # Override Halyard daemon's listen address
     cp /opt/halyard/config/* /tmp/config
