Updated the Gitops related files

diff --git a/charts/spinnaker/templates/configmap/halyard-init-script.yaml b/charts/spinnaker/templates/configmap/halyard-init-script.yaml
--- a/charts/spinnaker/templates/configmap/halyard-init-script.yaml
+++ b/charts/spinnaker/templates/configmap/halyard-init-script.yaml
@@ -7,7 +7,28 @@ metadata:
 data:
   init.sh: |
     #!/bin/bash
-
+    {{- if .Values.halyard.gitops.enabled }}
+    rm -rf /tmp/spinnaker/.hal
+    GIT_USER=`echo $GIT_USER | sed 's/ *$//g'`
+    GIT_TOKEN=`echo $GIT_TOKEN | sed 's/ *$//g'`
+    git -c {{ .Values.halyard.gitops.repo.configArgs }} clone $GIT_CLONE_PARAM -b {{ .Values.halyard.gitops.repo.halConfigBranch }} /tmp/spinnaker/test 2>/tmp/tmp.log
+    if [[ $? != 0 ]]; then
+       echo "ERROR: Failed while trying to execute:"
+       echo "git -c http.sslVerify=false clone $GIT_CLONE_PARAM -b {{ .Values.halyard.gitops.repo.halConfigBranch }} /tmp/spinnaker/test" | sed s/$GIT_TOKEN/\<TOKEN_REDACTED\>/g
+       sed s/$GIT_TOKEN/\<TOKEN_REDACTED\>/g /tmp/tmp.log
+       echo "####"
+       echo "Correct baseUrlHostName, organization, username, token and repository in values.yaml and re-execute 'helm upgrade --install ....' command"
+       echo "   It is possible that you need to use repoType as stash instead of git. Please check the documentation."
+       echo "To expedite the restart, wait for 60 seconds and delete the spinnaker-halyard-0 pod from another window"
+       exit 4
+    fi
+    cp -r /tmp/spinnaker/test// /tmp/spinnaker/.hal
+    rm -rf /tmp/spinnaker/test
+    printf 'server.address: 0.0.0.0\n' > /tmp/config/halyard-local.yml
+    if [ -f /tmp/spinnaker/.hal/halyard.yaml ]; then
+    cp /tmp/spinnaker/.hal/halyard.yaml /tmp/config
+    fi
+    {{- else }}
     # Override Halyard daemon's listen address
     cp /opt/halyard/config/* /tmp/config
     printf 'server.address: 0.0.0.0\n' > /tmp/config/halyard-local.yml
@@ -42,4 +63,5 @@ data:
     {{- if hasKey .Values.halyard "additionalInitScript" }}
     # additionalInitScript
     {{ tpl .Values.halyard.additionalInitScript $ | indent 4 }}
+    {{- end }}
     {{- end }}
